# Generated by Django 3.1.3 on 2020-12-03 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_hashtag'),
        ('home', '0008_auto_20201202_1407'),
    ]

    operations = [
    ]
