# Generated by Django 3.1.3 on 2020-12-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_merge_20201202_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
