# Generated by Django 3.1.3 on 2020-12-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201204_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='og_tweet',
            field=models.IntegerField(),
        ),
    ]
