# Generated by Django 3.1.3 on 2020-12-05 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_tweet_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='og_tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='home.tweet'),
        ),
    ]
