# Generated by Django 3.1.3 on 2020-12-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20201204_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='children',
        ),
        migrations.AddField(
            model_name='tweet',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='_tweet_children_+', to='home.Tweet'),
        ),
    ]
